# Generated by Django 2.2.4 on 2019-09-11 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import readyApps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('apikey_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apikey Value')),
                ('apikey_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apikey ID')),
                ('usage_plan_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usage Plan ID')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flow_user_ready_app',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReadyAppImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=2083, null=True, upload_to=readyApps.models.image_directory_path, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='readyApps.ReadyApps')),
            ],
            options={
                'db_table': 'flow_user_ready_app_image',
                'ordering': ('created_at',),
            },
        ),
    ]
