# Generated by Django 2.2.4 on 2019-09-19 06:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyApps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyapps',
            name='ready_apis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readyapps',
            name='reference_url',
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
