# Generated by Django 2.2.4 on 2019-09-01 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_auto_20190831_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='phone',
        ),
        migrations.AddField(
            model_name='profiles',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(default=None, max_length=50, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, max_length=2083, null=True, upload_to=profiles.models.profile_directory_path, verbose_name='Profile Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flow_user_profile_picture',
                'ordering': ('created_at',),
            },
        ),
    ]
