# Generated by Django 2.2.4 on 2019-08-31 09:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('user_type', models.CharField(blank=True, choices=[('AD', 'Admin'), ('IN', 'Individual'), ('CO', 'Company')], default='IN', max_length=2, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active status')),
                ('complete', models.BooleanField(default=False, verbose_name='Profile Complete')),
                ('staff', models.BooleanField(default=False, verbose_name='Staff status')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin status')),
                ('verified', models.BooleanField(default=False, verbose_name='Verification status')),
                ('steps', models.CharField(blank=True, choices=[('NS', 'Not Started'), ('NA', 'Not Applicable'), ('CP', 'Complete')], default='NS', max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flow_user',
                'ordering': ('created_at',),
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
