# Generated by Django 2.2.4 on 2019-09-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('created_at',), 'verbose_name_plural': 'Users'},
        ),
    ]
