# Generated by Django 2.2.4 on 2019-09-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190925_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verified',
            field=models.BooleanField(default=True, verbose_name='Verified'),
        ),
    ]
