# Generated by Django 2.2.4 on 2019-09-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('tagline', models.CharField(max_length=255, verbose_name='Tagline')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_url', models.CharField(blank=True, max_length=2083, null=True, verbose_name='Image URL')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('reference_url', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Modules',
                'db_table': 'flow_module',
                'ordering': ('created_at',),
            },
        ),
    ]
