# Generated by Django 2.2.4 on 2019-09-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='reference_url',
            field=models.SlugField(unique=True),
        ),
    ]
