# Generated by Django 2.2.4 on 2019-09-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20190918_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='image_url',
            field=models.CharField(blank=True, max_length=2083, null=True, verbose_name='Image URL'),
        ),
    ]
