# Generated by Django 2.2.4 on 2019-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Plan Name')),
                ('operations', models.IntegerField(default=0, verbose_name='Operations')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('total_count', models.IntegerField(default=0)),
                ('quota_limit', models.IntegerField(default=0)),
                ('burst_limit', models.IntegerField(default=0)),
                ('rate_limit', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('content', models.TextField(blank=True, null=True)),
                ('plan_razor_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razor Plan ID')),
                ('plan_aws_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='AWS Plan ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flow_plan',
                'ordering': ('operations',),
            },
        ),
    ]
