# Generated by Django 2.2.4 on 2019-09-25 13:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import readyApis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyApiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'flow_ready_api_category',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReadyApis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('tagline', models.CharField(max_length=255, verbose_name='Tagline')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image_url', models.CharField(blank=True, max_length=2083, null=True, verbose_name='Image')),
                ('cloud_url', models.CharField(max_length=255, unique=True)),
                ('usage_plan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Usage Plan')),
                ('use_cases', models.TextField(blank=True, null=True, verbose_name='Use Cases')),
                ('apikey_stage', models.CharField(blank=True, max_length=2083, null=True, verbose_name='Apikey Stage')),
                ('recommendations', models.SmallIntegerField(default=0, verbose_name='Recommendations')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, null=True, size=None)),
                ('reference_url', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readyApis.ReadyApiCategory')),
            ],
            options={
                'verbose_name_plural': 'Ready Apis',
                'db_table': 'flow_ready_api',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReadyApiMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, max_length=255, null=True, upload_to=readyApis.models.media_directory_path, verbose_name='Media')),
                ('url', models.CharField(blank=True, max_length=2083, null=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readyApis.ReadyApiCategory')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'db_table': 'flow_ready_api_media',
                'ordering': ('created_at',),
            },
        ),
    ]
