# Generated by Django 2.2.4 on 2019-09-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readyApis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readyapis',
            name='tagline',
            field=models.CharField(default=None, max_length=255, verbose_name='Tagline'),
            preserve_default=False,
        ),
    ]
