# Generated by Django 2.2.4 on 2019-09-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readyApis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readyapis',
            old_name='usage_plan',
            new_name='usage_plan_id',
        ),
    ]
