# Generated by Django 2.2.4 on 2019-09-01 05:44

import apis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('trial', models.BooleanField(default=False, verbose_name='Has Trial')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('recommendations', models.SmallIntegerField(default=0, verbose_name='Recommendations')),
                ('price', models.FloatField(default=0.0, verbose_name='Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('documentation', models.TextField(blank=True, null=True, verbose_name='Documentation')),
                ('use_cases', models.TextField(blank=True, null=True, verbose_name='Use Cases')),
                ('image', models.CharField(blank=True, max_length=2083, null=True, verbose_name='Image')),
                ('video', models.CharField(blank=True, max_length=2083, null=True, verbose_name='Video')),
                ('cloud_url', models.CharField(max_length=255, unique=True)),
                ('cloud', models.CharField(blank=True, max_length=2083, null=True, verbose_name='Cloud Id')),
                ('apikey_stage', models.CharField(blank=True, max_length=2083, null=True, verbose_name='Apikey Stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flow_api',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApiCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('trial', models.BooleanField(default=False, verbose_name='Has Trial')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'flow_api_category',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=2083, null=True, verbose_name='Image URL')),
                ('api_image', models.ImageField(blank=True, max_length=255, null=True, upload_to=apis.models.api_image_directory_path, verbose_name='API Image')),
                ('trial', models.BooleanField(default=False, verbose_name='Is trial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Api')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.ApiCategory')),
            ],
            options={
                'db_table': 'flow_api_images',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='api',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.ApiCategory'),
        ),
    ]
