# Generated by Django 2.2.4 on 2019-09-01 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api',
            new_name='Apis',
        ),
    ]
