# Generated by Django 2.2.4 on 2019-10-11 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0003_auto_20190928_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyApiUsageBuckets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.IntegerField(default=100, verbose_name='Bucket (Quota)')),
                ('usage', models.IntegerField(default=0, verbose_name='Usage (Calls Made)')),
                ('threshold', models.IntegerField(default=0, verbose_name='Threshold (Alert User of Usage)')),
                ('active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Apps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ready Api Usage Buckets',
                'db_table': 'flow_user_ready_api_usage_bucket',
                'ordering': ('created_at',),
            },
        ),
    ]
