# Generated by Django 2.2.4 on 2019-09-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='reference_url',
            field=models.SlugField(),
        ),
    ]
