# Generated by Django 2.2.4 on 2019-09-28 08:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20190927_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apps',
            old_name='active_apis',
            new_name='custom_apis',
        ),
        migrations.AddField(
            model_name='apps',
            name='notebook',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='apps',
            name='ready_apis',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), blank=True, null=True, size=None),
        ),
    ]
